name: Build DEB

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 安装基础依赖与 ldid
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev git wget
          wget https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      - name: 安装 Theos 环境
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: 下载 iOS SDK
        run: |
          rm -rf $HOME/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git $HOME/theos/sdks

      - name: 开始编译插件
        run: |
          make clean
          make package

      - name: 上传 deb 文件
        uses: actions/upload-artifact@v4
        with:
          name: 编译出的插件deb
          path: ./packages/*.deb
